- id: ironic-copy-bootstrap-keys
  type: copy_files
  role: ['ironic']
  required_for: [pre_deployment_end]
  requires: [pre_deployment_start]
  parameters:
    permissions: '0600'
    dir_permissions: '0700'
    files:
      - src: /var/lib/fuel/keys/ironic/bootstrap.rsa
        dst: /var/lib/astute/ironic/bootstrap.rsa

- id: ironic-haproxy
  groups: ['primary-controller', 'controller']
  type: puppet
  required_for: [ironic-api]
  requires: [openstack-haproxy, ironic-vips]
  parameters:
    puppet_manifest: puppet/manifests/haproxy.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-network-ovs
  groups: ['primary-controller', 'controller', 'ironic']
  type: puppet
  required_for: [virtual_ips, ironic-vips, ironic-openstack-network-compute]
  requires: [netconfig]
  parameters:
    puppet_manifest: puppet/manifests/network-ovs.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-physnets
  groups: ['primary-controller', 'controller']
  type: puppet
  required_for: [ironic-network-openstack]
  requires: [ironic-network-ovs, openstack-network]
  parameters:
    puppet_manifest: puppet/manifests/network-physnets.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-openstack-network-compute
  groups: ['ironic']
  type: puppet
  required_for: [ironic-physnets-conductor]
  requires: [ironic-compute]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openstack-network/openstack-network-compute.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: ironic-physnets-conductor
  groups: ['ironic']
  type: puppet
  required_for: [deploy_end]
  requires: [ironic-openstack-network-compute]
  parameters:
    puppet_manifest: puppet/manifests/network-physnets-conductor.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-vips
  groups: ['primary-controller', 'controller']
  type: puppet
  required_for: [ironic-haproxy]
  requires: [openstack-controller, ironic-network-ovs]
  parameters:
    puppet_manifest: puppet/manifests/vips.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-network-openstack
  groups: ['primary-controller', 'controller']
  type: puppet
  required_for: [deploy_end]
  requires: [openstack-network, ironic-network-ovs]
  parameters:
    puppet_manifest: puppet/manifests/network-openstack.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-db
  groups: ['primary-controller']
  type: puppet
  required_for: [ironic-api]
  requires: [database]
  parameters:
    puppet_manifest: puppet/manifests/db.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-upload-images
  role: ['primary-controller']
  type: shell
  required_for: [ironic-conductor-config]
  requires: [enable_quorum, enable_rados]
  parameters:
    cmd: ruby upload_images.rb
    retries: 3
    interval: 20
    timeout: 180

- id: ironic-conductor-config
  role: ['ironic']
  type: puppet
  required_for: [post_deployment_end]
  requires: [ironic-upload-images]
  parameters:
    puppet_manifest: puppet/manifests/ironic-conductor-config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-swift-key
  role: ['primary-controller']
  type: shell
  required_for: [post_deployment_end]
  requires: [enable_quorum, enable_rados]
  parameters:
    cmd: ruby post_swift_key.rb
    retries: 3
    interval: 20
    timeout: 180

- id: ironic-api
  groups: ['primary-controller', 'controller']
  type: puppet
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [openstack-controller, ironic-db, ironic-vips, ironic-haproxy]
  parameters:
    puppet_manifest: puppet/manifests/ironic.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-conductor-network
  groups: ['ironic']
  type: puppet
  required_for: [ironic-conductor]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: puppet/manifests/network-conductor.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-conductor
  groups: ['ironic']
  type: puppet
  required_for: [ironic-compute]
  requires: [ironic-conductor-network]
  parameters:
    puppet_manifest: puppet/manifests/ironic-conductor.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic-compute
  groups: ['ironic']
  type: puppet
  required_for: [ironic-openstack-network-compute]
  requires: [ironic-conductor]
  parameters:
    puppet_manifest: puppet/manifests/ironic-compute.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: baremetal-firewall
  role: '*'
  type: puppet
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: puppet/manifests/baremetal-firewall.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600

- id: ironic
  type: group
  role: [ironic]
  tasks:
    - fuel_pkgs
    - hiera
    - globals
    - logging
    - tools
    - netconfig
    - hosts
    - firewall
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel
